{"name": "test_accountexist", "status": "failed", "statusDetails": {"message": "AssertionError: assert '无效的session' == '手机号已经存在'\n  - 手机号已经存在\n  + 无效的session", "trace": "self = <testcase.ceshicase.TestMgmt object at 0x00000204F736A208>\n\n    def test_accountexist(self):#创建账号手机号重复\n        self.logger = log.Logger\n        base_url = cf.get(\"db\", \"base_url1\") + \"createAccount\"\n        data = {\"name\": \"展rgrgb\", \"phone\": self.g[\"m\"], \"sex\": \"1\"}\n        file = {\"file\": (\"u.jpg\", open('D:/a/u.jpg', \"rb\"), \"image/jpeg\")}\n        r = requests.post(url=base_url, headers=headers, files=file, data=data).json()\n        self.logger.info(r)\n>       assert r[\"resultMessage\"] ==\"手机号已经存在\"\nE       AssertionError: assert '无效的session' == '手机号已经存在'\nE         - 手机号已经存在\nE         + 无效的session\n\nceshicase.py:168: AssertionError"}, "attachments": [{"name": "log", "source": "ac242585-e1e3-474e-82be-c5055304194e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "80a43f6a-37e5-4645-8360-959db711b56d-attachment.txt", "type": "text/plain"}], "start": 1626248777715, "stop": 1626248777896, "uuid": "5a251cc9-378f-4a7c-b81e-201c1e90f524", "historyId": "bcf5c339a1e53896f21fe24202458d98", "testCaseId": "4f846ec70364b8e5df859076026cef55", "fullName": "testcase.ceshicase.TestMgmt#test_accountexist", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "ceshicase"}, {"name": "subSuite", "value": "TestMgmt"}, {"name": "host", "value": "LAPTOP-1V0QHO6O"}, {"name": "thread", "value": "22600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.ceshicase"}]}